SETTING_DATA_INPUT_DIR = "../data/raw/"
SETTING_MAIN_OUTPUT_DIR = "../data/training_runs"
SETTING_DATA_PRODUCTS_SUBDIR = "data_products"
SETTING_PLOTS_SUBDIR = "plots"

SETTING_GAME_WIDTH = 25

SETTING_TRAIN_FRACTION = 0.8
SETTING_VAL_FRACTION = 0.1
SETTING_TEST_FRACTION = 0.1

SETTING_NUM_EPOCHS = 100
SETTING_BATCH_SIZE = 32
SETTING_LEARNING_RATE = 0.001
SETTING_P_DROPOUT = 0.2
SETTING_TEST_FREQ = 25
